import pygame
import os

EMPTY = 0
BLACK = 1
WHITE = -1
WIDTH, HEIGHT = 600, 600
BOARD_COLOR = (0, 180, 0)
ROWS, COLS = 8, 8
SQUARE_SIZE = WIDTH//ROWS
BLACK_COLOR = (0, 0, 0)
WHITE_COLOR = (255, 255, 255)
PIECE_RADIUS = SQUARE_SIZE // 2 - 5

board = [
    [2,     2, EMPTY, EMPTY, WHITE, EMPTY,     2,     2],
    [2, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,     2],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, BLACK, WHITE, EMPTY, WHITE, EMPTY],
    [EMPTY, WHITE, EMPTY, WHITE, BLACK, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [2, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,     2],
    [2,     2, EMPTY, EMPTY, WHITE, EMPTY,     2,     2]
]
